// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqAJfULJuBhNbL4obNwkkpSOpXkd0k0tY',
    appId: '1:73479198925:web:1ca2047a60e3e6ae6e3184',
    messagingSenderId: '73479198925',
    projectId: 'edu-ecommerce-1182e',
    authDomain: 'edu-ecommerce-1182e.firebaseapp.com',
    storageBucket: 'edu-ecommerce-1182e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExulMr8AhRNchwA9OiAlb9JQW4wyKK1k',
    appId: '1:73479198925:android:76eb82c67d1cd88a6e3184',
    messagingSenderId: '73479198925',
    projectId: 'edu-ecommerce-1182e',
    storageBucket: 'edu-ecommerce-1182e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2TTt620fpRhMITaUQs6WSYnzl5CYFyOc',
    appId: '1:73479198925:ios:ca3f7309de5609326e3184',
    messagingSenderId: '73479198925',
    projectId: 'edu-ecommerce-1182e',
    storageBucket: 'edu-ecommerce-1182e.appspot.com',
    iosClientId: '73479198925-2rlepqbjkrd4gtuet7gm7f7dlc0rgb0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduEcommerceDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2TTt620fpRhMITaUQs6WSYnzl5CYFyOc',
    appId: '1:73479198925:ios:ca3f7309de5609326e3184',
    messagingSenderId: '73479198925',
    projectId: 'edu-ecommerce-1182e',
    storageBucket: 'edu-ecommerce-1182e.appspot.com',
    iosClientId: '73479198925-2rlepqbjkrd4gtuet7gm7f7dlc0rgb0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduEcommerceDemo',
  );
}
